Make namespace optional and combine with hookName using dot notation
WordPress/packages pull request #108
Opened 2018-04-11 16:42 UTC by adamsilverstein

This PR seeks to remove the namespace parameter and instead enable support for an optional namespace added to the hookName using dot notation, in the form `hookName.vendor/plugin/function`. Fixes https://github.com/WordPress/packages/issues/107.

Includes updated docs: https://github.com/WordPress/packages/blob/fda1b56a606afccf40b86867f80710f6895559bb/packages/hooks/README.md

* after this change, periods are no longer allowed in the hook name - instead they are used to separate the hook name from the namespaced function name.
* when a namespace is omitted from a call to removeFilters/Actions, all callbacks on that hook name are removed.
* refactored all tests

2018-04-16 08:06 UTC, gziolo commented
@adamsilverstein, thanks for opening this PR. It seems like the proposed approach is the best possible moving forward. I have only one concern, which is a blocker in my opinion. This won't work with Gutenberg because of the way we name our hooks. See: https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/.

Some examples:
- `blocks.registerBlockType`
- `blocks.BlockEdit`
- `blocks.getSaveElement`
- `blocks.getSaveContent.extraProps`

It won't work properly with what you proposed and I'm afraid it's too late to change those names inside Gutenberg. Can we seek for a better naming convention that would work as you proposed, but would also ensure that Gutenberg hooks will work as before?

Some alternatives are:
* `blocks.getSaveContent.extraProps/core/generated-class-name/save-props`
* `blocks.getSaveContent.extraProps#core/generated-class-name/save-props`

I think we have 2 different styles because there were 2 different validation method for both params. We can update 2nd part to match whatever we agree upon in here.

2018-04-16 08:11 UTC, gziolo requested changes

2018-04-16 08:11 UTC, gziolo commented on packages/hooks/README.md
> +// Create a hooks instance.
It's not wrapped in code so we should either do it or remove preceding `//` :)

2018-04-16 08:11 UTC, gziolo commented on packages/hooks/src/validateHookName.js
> +		console.error( 'The hook name can only contain numbers, letters, dashes and underscores.' );
Gutenberg and its hooks depend on periods :(

2018-04-17 12:38 UTC, herregroen commented
I quite like this proposal. Feels very natural and fitting for Javascript.

It could be worth exploring if adding console warnings when namespaces are omitted is something we want to encourage good standards, perhaps as an option that can be passed to `createHooks` so projects that expect multiple plugins can enable while projects that have no need for it can disable it.

Regarding the above. While periods would be preferred in my opinion due to the consistency with jQuery we could of course replace them with say a `#` or some other character.

2018-04-24 12:46 UTC, adamsilverstein commented
I took a slightly different approach in https://github.com/WordPress/packages/pull/113 by making the namespace parameter optional, but not moving it into the hook parameter. This will give us better back compat for existing use cases, and work correctly with Gutenberg.

For plugins, the idea would be to have registerPlugin pass the plugin namespace to created hooks.

```
registerPlugin( 'my-namespace', {
...
hooks: [ 
  'blocks.BlockEdit': function() { ... },
etc...
]
```

2018-07-09 13:14 UTC, closed without merging

2018-07-09 13:14 UTC, ntwb commented
Issue moved to [WordPress/gutenberg #7820](https://github.com/WordPress/gutenberg/issues/7820) via [**ZenHub**](https://www.zenhub.com/)